"""Change invested field name

Revision ID: d8e6b1b298ce
Revises: 106859e67805
Create Date: 2025-04-20 13:11:03.625036

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8e6b1b298ce'
down_revision: Union[str, None] = '106859e67805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('invested_amount', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('charityproject', 'invest_amount')
    op.add_column('donation', sa.Column('invested_amount', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('donation', 'invest_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('invest_amount', sa.INTEGER(), nullable=False))
    op.drop_column('donation', 'invested_amount')
    op.add_column('charityproject', sa.Column('invest_amount', sa.INTEGER(), nullable=False))
    op.drop_column('charityproject', 'invested_amount')
    # ### end Alembic commands ###
